# Generated by Django 4.2.24 on 2025-11-09 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_liked_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
