# Generated by Django 4.2.24 on 2025-11-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page_rank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
