# Generated by Django 4.2.24 on 2025-11-21 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 21, 2, 49, 26, 964620, tzinfo=datetime.timezone.utc)),
        ),
    ]
