# Generated by Django 4.2.24 on 2025-11-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_comment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
