# Generated by Django 4.2.24 on 2025-11-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
