# Generated by Django 4.2.24 on 2025-11-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_comments',
            field=models.ManyToManyField(blank=True, related_name='liked_comment', to='network.comment'),
        ),
    ]
