# Generated by Django 4.2.24 on 2025-11-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_user_liked_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_rank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
