# Generated by Django 4.2.24 on 2025-11-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_comment_comment_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.URLField(blank=True),
        ),
    ]
