# Generated by Django 4.2.24 on 2025-11-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='engagement_time',
            field=models.IntegerField(default=0),
        ),
    ]
