# Generated by Django 4.2.24 on 2025-12-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_post_engagement_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1200),
        ),
    ]
