# Generated by Django 4.2.24 on 2025-12-06 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_user_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_rank',
        ),
        migrations.RemoveField(
            model_name='post',
            name='engagement_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='page_rank',
        ),
        migrations.CreateModel(
            name='PostEngagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_rank', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('engagement_time', models.IntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='network.post')),
            ],
        ),
        migrations.CreateModel(
            name='CommentEngagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_rank', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='network.comment')),
            ],
        ),
    ]
