# Generated by Django 4.2.24 on 2025-12-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_alter_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentengagement',
            name='last_calculated',
        ),
        migrations.RemoveField(
            model_name='postengagement',
            name='last_calculated',
        ),
    ]
